
//com este import é possivel importar o css do bulma para toda aplicação
import 'bulma/css/bulma.css'
import '@/components/common/loader/loader.css'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
